name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p downloads
      - run: wget https://cloud.3mdeb.com/index.php/s/UQQVYrNIhg7ddwj/download -O downloads/kernels.tar.gz
- uses: actions/upload-artifact@master
  with:
    name: my-artifact
    path: downloads
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
