name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: download Dependencies
         uses: actions/checkout@v1
      - name: wget Dependencies
      uses: wei/wget@v1
      with:
        args: -O downloads/kernels.tar.gz https://cloud.3mdeb.com/index.php/s/UQQVYrNIhg7ddwj/download
      #- run: wget https://cloud.3mdeb.com/index.php/s/UQQVYrNIhg7ddwj/download -O downloads/kernels.tar.gz
- uses: actions/upload-artifact@master
  with:
    name: my-artifact
    path: downloads
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)

